<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command.proto

namespace PhluxorExample\Metadata;

class Command
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xF5\x01\x0A\x0Dcommand.proto\x12\x16PhluxorExample.Command\"\x1E\x0A\x0BStartsClass\x12\x0F\x0A\x07subject\x18\x01 \x01(\x09\"\x1E\x0A\x0BPrepareTest\x12\x0F\x0A\x07subject\x18\x01 \x01(\x09\"\x1C\x0A\x09StartTest\x12\x0F\x0A\x07subject\x18\x01 \x01(\x09\"+\x0A\x0ASubmitTest\x12\x0F\x0A\x07subject\x18\x01 \x01(\x09\x12\x0C\x0A\x04name\x18\x02 \x01(\x09\"\x1D\x0A\x0AFinishTest\x12\x0F\x0A\x07subject\x18\x01 \x01(\x09B\x1A\xE2\x02\x17PhluxorExample\\Metadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

